### ISSUE TITLE
Homework Feedback - HTML/CSS week 2

### ISSUE THREAD

**Issue by susaneme** [tiago86g/hyf-homework#1]
Hi Tiago :) 

What I can tell? You simply nailed it !!! 🎉  Congratulations for all the hard work you put in here! But also congratulations for taking it seriously and getting the most of the classes as you’ve doing !👏 🥇 💯 

 - I am impressed how you got the subtle change in the layout from the desktop to the mobile version, where the ‘Practical development’ comes before the ‘Web development ...’ . Really well done! 🙃 You have definitely an analytical eye 👍 
- You cared about converting the design specification  precisely , you are going to be a complete developer, as you understand the design as well.
- For the google maps part, I would encourage to research a little to see how to put a interactive map there. I can give you some tips, as for example this site [here](https://www.embedgooglemap.net/). 
- Footers and headers are simply perfect, converting into vertical items. ✅ - 
- Your HTML itself, is organized, clean and most importantly semantic!! Using the correct tags for the right containers 
- You used classes in a perfect portion, not overusing it and make you markup complex ✔️ 
- I would recommend try to name your classes in a more meaningful way, for example where you say `div class=“container-4”` you could have named something like `div class=“gallery”` 👍 
- Another small observation in your media query, try to ‘reset’ your padding or margin or give it a smaller value, as when scaling down, I can see that there is extra padding in the right side. 

You should be proud of yourself! WELL DONE 😍 Congratulations! 👏

**Comment by tiago86g** [comment]
Thanks  for the feedback Susane, I'll on those points to fix it :)
