### ISSUE TITLE
Homework Feedback - JS1-Week2

### ISSUE THREAD

**Issue by Swapna-Sahu** [tiago86g/hyf-homework#4]
Well done. I think you have missed saving your Candy Helper Task. 
Here is my feedback for your task.

Student Manager Task :
Missing this test code - You cannot add an empty string to a class.
you have to write a one statement for empty string input.

Candy Helper Task :
Missing Task

Reply to me once you have completed all task. except optional. 
Enjoy  coding !

**Comment by tiago86g** [comment]
Thanks for the feedback Swapna :)
I'll fix it soon. The "Helper Task" is optional but I will try to do it anyway

**Comment by tiago86g** [comment]
fixed code in https://github.com/tiago86g/hyf-homework/pull/27/commits/96c02afbe9aea978a3a498f7f3b694c602ca9a60
