### ISSUE TITLE
Homework Feedback JS1-Week3

### ISSUE THREAD

**Issue by Swapna-Sahu** [tiago86g/hyf-homework#5]
Good job 👍 . Almost everything looks good. I can see fast learning here.

Item array removal Task -

Task was removing random name using random method.
Here, you are choosing the position and removing it.
For removing random name from the array either you use for loop inside If statement or you can just check the index of the element which is matching then slice it.

Enjoy coding 👍

**Comment by tiago86g** [comment]
Thanks Swapna I finally fixed this homework here
https://github.com/tiago86g/hyf-homework/pull/28/commits/ca395459a7ad58dfa2fb152191db0e9b3b73886d
